PMSWebApplication/Models/DomainModels/Payment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PMSWebApplication.Models.DomainModels
{
    public class Payment
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Project Name")]
        public int ProjectId { get; set; }
        public virtual Project Project { get; set; }

        [Required]
        [Display(Name = "Task Name")]
        public int TaskId { get; set; }
        public virtual Task Task { get; set; }

        [Display(Name = "Task Stage")]
        public string TaskStages { get; set; }

        [Required]
        [Display(Name = "Invoice No")]
        public int InvoiceNo { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Payment Date")]
        [Column(TypeName = "date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? PayDate { get; set; }

        [Required]
       [Display(Name = "Pay Amount")]
        public decimal? PaymentAmount { get; set; }

        [Required]
        [Display(Name = "Payment Method")]
        public string PayMethod { get; set; }

        [Required]
        [StringLength(150)]
        [Display(Name = "Description")]
        public string PayDiscription { get; set; }
    }
}

PMSWebApplication/Models/Duepayment.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace PMSWebApplication.Models
{
    public class Duepayment
    {

        public int Id { get; set; }

        public string ProjectName { get; set; }

        //public string ClientName { get; set; }

        public DateTime? Deadline { get; set; }

        public string TaskName { get; set; }

        [Display(Name = "Paid Amount")]
        public decimal? PaidAmount { get; set; }
    }
}

PMSWebApplication/Models/UpcommingPayment.cs
using System;

namespace PMSWebApplication.Models
{
    public class UpcommingPayment
    {
        public int Id { get; set; }

        public string ProjectName { get; set; }

        public string TaskName { get; set; }

        public string TaskStages { get; set; }

        public decimal? Payment { get; set; }

        public DateTime? Deadline { get; set; }
    }
}

PMSWebApplication/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PMSWebApplication.Models;
using PMSWebApplication.Models.DomainModels;
using CrystalDecisions.CrystalReports.Engine;
using System.IO;

namespace PMSWebApplication.Controllers
{
    public class PaymentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Payments
        public async Task<ActionResult> Index()
        {
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "ProjectName");
            var payments = db.Payments.Include(p => p.Project).Include(p => p.Task);
            return View(await payments.ToListAsync());
        }

        [HttpPost]
        public async Task<ActionResult> Index(int ProjectId)
        {
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "ProjectName");
            var payments = db.Payments.Include(p => p.Project).Include(p => p.Task).Where(p=>p.ProjectId==ProjectId);
            return View(await payments.ToListAsync());
        }
       


        // GET: Payments/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payment payment = await db.Payments.FindAsync(id);
            if (payment == null)
            {
                return HttpNotFound();
            }
            return View(payment);
        }

        // GET: Payments/Create
        public ActionResult Create()
        {
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "ProjectName");
            ViewBag.TaskId = new SelectList(db.Tasks, "Id", "TaskName");
            return View();
        }
       



        // POST: Payments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,ProjectId,TaskId,InvoiceNo,PayDate,PaymentAmount,PayMethod,PayDiscription")] Payment payment)
        {
            if (ModelState.IsValid)
            {
                db.Payments.Add(payment);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "ProjectName", payment.ProjectId);
            ViewBag.TaskId = new SelectList(db.Tasks, "Id", "TaskName", payment.TaskId);
            return View(payment);
        }

        


        // GET: Payments/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payment payment = await db.Payments.FindAsync(id);
            if (payment == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "ProjectName", payment.ProjectId);
            ViewBag.TaskId = new SelectList(db.Tasks, "Id", "TaskName", payment.TaskId);
            return View(payment);
        }

        // POST: Payments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,ProjectId,TaskId,InvoiceNo,PayDate,PaymentAmount,PayMethod,PayDiscription")] Payment payment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(payment).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "ProjectName", payment.ProjectId);
            ViewBag.TaskId = new SelectList(db.Tasks, "Id", "TaskName", payment.TaskId);
            return View(payment);
        }

        // GET: Payments/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payment payment = await db.Payments.FindAsync(id);
            if (payment == null)
            {
                return HttpNotFound();
            }
            return View(payment);
        }

        // POST: Payments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Payment payment = await db.Payments.FindAsync(id);
            db.Payments.Remove(payment);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // GET: Upcomming Payements
        public async Task<ActionResult> UpCommingPayments()
        {
            var tasks = await db.Tasks.Where(x => x.Deadline > DateTime.Today).ToListAsync();
            List<UpcommingPayment> upcommingPayemets = new List<UpcommingPayment>();
           
            foreach (var task in tasks)
            {
                UpcommingPayment payment = new UpcommingPayment();
                var project = await db.Projects.FindAsync(task.ProjectId);
                var count = db.Payments.Where(x => x.ProjectId == project.Id && x.TaskId == task.Id).Select(x => x.PaymentAmount).Sum();

                payment.Id = task.Id;
                payment.Payment = (task.TaskWisePayment - count);
                payment.TaskName = task.TaskName;
                payment.ProjectName = project.ProjectName;
                payment.Deadline = task.Deadline;

                upcommingPayemets.Add(payment);
            }
            return View(upcommingPayemets);
     
        }
        public async Task<ActionResult> Duepayment()
        {
            var tasks = await db.Tasks.Where(x => x.Deadline > DateTime.Today).ToListAsync();
            List<Duepayment> duepayment = new List<Duepayment>();

            foreach (var task in tasks)
            {
                Duepayment paid = new Duepayment();
                var project = await db.Projects.FindAsync(task.ProjectId);
                var total = db.Payments.Where(x => x.ProjectId == project.Id && x.TaskId == task.Id).Select(x => x.PaymentAmount).Sum();

                paid.Id = task.Id;
                paid.PaidAmount = total;
                paid.TaskName = task.TaskName;
                paid.ProjectName = project.ProjectName;
                paid.Deadline = task.Deadline;

                duepayment.Add(paid);
            }
            return View(duepayment);

        }

        public async Task<ActionResult> ExportPaymentReport()
        {
            //empEntities context = new empEntities();

            ReportDocument rd = new ReportDocument();
            rd.Load(Path.Combine(Server.MapPath("//Reports//PaymentReport.rpt")));
            //rd.SetDataSource(db.Payments.Select(c => new
            //{
            //    ProjectId = c.ProjectId,
            //    TaskId = c.TaskId
            //}).ToList());

            var project = await db.Projects.ToListAsync();
            //var project = await db.Payments.ToListAsync();

            foreach (var task in project)
            {
                rd.SetDataSource(db.Payments.Where(x => x.ProjectId == task.Id).Select(c => new
                {
                    ProjectId = c.ProjectId,
                    TaskId = c.TaskId
                }).ToList());

            }                                                                                                                                                                                                                               
                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

PMSWebApplication/Controllers/ReportController.cs
using CrystalDecisions.CrystalReports.Engine;
using PMSWebApplication.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PMSWebApplication.Controllers
{
    public class ReportController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Report
        public ActionResult Index()
        {
            return View();
        }

        public async System.Threading.Tasks.Task<ActionResult> ExportPaymentReport()
        {
            //empEntities context = new empEntities();

            ReportDocument rd = new ReportDocument();
            //var tasks = await db.Tasks.Where(x => x.Deadline > DateTime.Today).ToListAsync();
            var project = await db.Projects.ToListAsync();
            rd.Load(Path.Combine(Server.MapPath("//Report//PaymentReport.rpt")));
            foreach (var task in project)
            {
                rd.SetDataSource(db.Payments.Where(x => x.ProjectId == task.Id).Select(c => new
                {
                    //Projectname = task.ProjectName,
                    ProjectId = c.ProjectId,
                    TaskId = c.TaskId
                }).ToList());
            }              

            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();


            rd.PrintOptions.PaperOrientation = CrystalDecisions.Shared.PaperOrientation.Landscape;
            rd.PrintOptions.ApplyPageMargins(new CrystalDecisions.Shared.PageMargins(5, 5, 5, 5));
            rd.PrintOptions.PaperSize = CrystalDecisions.Shared.PaperSize.PaperA5;

            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            stream.Seek(0, SeekOrigin.Begin);

            return File(stream, "application/pdf", "PaymentReport.pdf");
        }

    }
}  
    

PMSWebApplication/Views/Payments/Create.cshtml
@model PMSWebApplication.Models.DomainModels.Payment

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Payment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProjectId, "ProjectId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProjectId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskId, "TaskId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TaskId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TaskId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InvoiceNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InvoiceNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InvoiceNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PayDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PayDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PayDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentAmount, "", new { @class = "text-danger" })
            </div>
        </div>
       
        

        <div class="form-group">
            @Html.LabelFor(model => model.PayMethod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <lable class="radio-inline">
                @Html.RadioButtonFor(model => model.PayMethod,"Credit", new { @name = "paymethod" })
                       Credit
                </lable>
                <lable class="radio-inline">
                    @Html.RadioButtonFor(model => model.PayMethod, "Cash", new { @name = "payMethod" })
                    Cash
                </lable>
                <lable class="radio-inline">
                    @Html.RadioButtonFor(model => model.PayMethod, "Cheque", new { @name = "payMethod" })
                    Cheque
                </lable>
                @Html.ValidationMessageFor(model => model.PayMethod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PayDiscription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PayDiscription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PayDiscription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List","Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PMSWebApplication/Views/Payments/Delete.cshtml
@model PMSWebApplication.Models.DomainModels.Payment

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Payment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Project.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Task.TaskName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Task.TaskName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InvoiceNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InvoiceNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PayDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PayDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PayMethod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PayMethod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PayDiscription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PayDiscription)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PMSWebApplication/Views/Payments/Details.cshtml
@model PMSWebApplication.Models.DomainModels.Payment

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Payment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Project.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Task.TaskName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Task.TaskName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InvoiceNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InvoiceNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PayDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PayDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PayMethod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PayMethod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PayDiscription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PayDiscription)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PMSWebApplication/Views/Payments/Duepayment.cshtml
@model IEnumerable<PMSWebApplication.Models.Duepayment>
@{
    ViewBag.Title = "Duepayment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Duepayment</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProjectName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Deadline)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TaskName)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.PaidAmount)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectName)
            </td>
            <th>
                @Html.DisplayFor(modelItem => item.Deadline)
            </th>
            <td>
                @Html.DisplayFor(modelItem => item.TaskName)
            </td>

            <th>
                @Html.DisplayFor(modelItem => item.PaidAmount)
            </th>
            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.Id })
                </td>*@
        </tr>
    }
</table>

PMSWebApplication/Views/Payments/Edit.cshtml
@model PMSWebApplication.Models.DomainModels.Payment

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Payment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectId, "ProjectId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProjectId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskId, "TaskId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TaskId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TaskId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InvoiceNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InvoiceNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InvoiceNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PayDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PayDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PayDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PayMethod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PayMethod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PayMethod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PayDiscription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PayDiscription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PayDiscription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PMSWebApplication/Views/Payments/Index.cshtml
@model IEnumerable<PMSWebApplication.Models.DomainModels.Payment>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Payment List</h2>

<p>
    @using (Html.BeginForm())


    {
        <div class="pull-right">
            <table>
                <tr>
                    <th>

                        @Html.DropDownList("ProjectId", null, htmlAttributes: new { @class = "form-control" })

                    </th>
                    <th>
                        <input type="submit" value="Search" />
                    </th>
                </tr>
            </table>
        </div>
        <table>
            <tr>
                <th>
                    @Html.ActionLink("Add Payment", "Create")
                </th>
                </tr>
            </table>

    }
</p>

<div>
    @Html.ActionLink("Download", "ExportPaymentReport", "Payments", new { @class = "btn btn-primary" }, null)
</div>    

<div>
    @Html.ActionLink("Download_PDF", "ExportPaymentReport", "Report", new { @class = "btn btn-primary" }, null)
</div>

<table class="table">

    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Project.ProjectName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Task.TaskName)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.InvoiceNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PayDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PaymentAmount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PayMethod)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PayDiscription)
        </th>
        <th></th>*@
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Project.ProjectName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Task.TaskName)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.InvoiceNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PayDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaymentAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PayMethod)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PayDiscription)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-primary btn-sm" }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-info btn-sm" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-warning btn-sm" })
            </td>*@
        </tr>

    }


</table>

PMSWebApplication/Views/Payments/UpcommingPayments.cshtml
@model IEnumerable<PMSWebApplication.Models.UpcommingPayment>

@{
    ViewBag.Title = "UpcommingPayments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>UpcommingPayments</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProjectName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TaskName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Payment)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Deadline)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProjectName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TaskName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Payment)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Deadline)
        </td>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>*@
    </tr>
}

</table>

PMSWebApplication/Views/Payments/View.cshtml
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View</h2>